version: '3.0'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./src/test/resources/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - "3310:3306"
    command: --init-file /data/application/init.sql

  app:
    image: identify-docker-image:latest
    container_name: identify-docker-container
    ports:
      - '8888:8888'
    depends_on:
      - mysql

volumes:
  db:
    driver: local