version: '3.0'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - ./src/test/resources/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - "3310:3306"
    command: --init-file /data/application/init.sql

  app:
    image: identify-docker-image:latest
    container_name: identify-docker-container
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bitespeed

volumes:
  db:
    driver: local